### PR TITLE
Some patches

### PR DESCRIPTION
**Pull request by c9s**
- Move phpunit.vim into ftplugin/php/   to let vim load plugin only when filetype is "php", which can reduce script loading.
- Add a Makefile to help install plugin easily.

### CODE REVIEW

**Comment by klokane** [comment]
Hi, I'm working currently on project in C++ so I've no time to work on this plugin. Thank you very much for your work.

Your changes I'll merge into master branche. But I'm not sure about Makefile. In my opinion it's very simple project to hold it's own Makefile.

**Comment by c9s** [comment]
You can choose to keep Makefile or remove it. :-)

**Comment by klokane** [comment]
Sure :) But I would like to know your mind around this.

**Comment by c9s** [comment]
I wrote the Makefile to auto-install vim scripts, generate vimball, make a dist file (tarball), or uninstall plugin files.  :-)

**Pull request closed without merging**
